### ISSUE TITLE
neo4j nodes are not moving anymore after overriding init.coffee

### ISSUE THREAD

**Issue by omurbekjk** [graphadvantage/neo4j-browser-images#3]
I was using your coffee script to override latest neo4j 3.3.1 docker image. It works fine, but nodes are not moving anymore when i select

**Comment by graphadvantage** [comment]
Thanks #omurbekj - I haven't tested it on 3.3 yet - let me take a look.

-----------
Just tested it with the latest build  [https://github.com/neo4j/neo4j-browser](url) , seems to work

Install like this - navigate to this folder
/neo4j-browser/src/browser/modules/D3Visualization/lib/visualization/renders/
rename init.coffee to init.coffee.old 
copy init.coffee from this neo4j-browser-images

yarn start will open the browser on port 8080

It may be related to the Docker image - hard to tell, LMK if you diagnose it

**Comment by graphadvantage** [comment]
<img width="686" alt="neo4j-browser-images" src="https://user-images.githubusercontent.com/5991751/35291506-52da4018-0022-11e8-835c-b232446c7563.png">

**Comment by omurbekjk** [comment]
Thanks. It worked when I used fresh neo4j-browser. How can I add another image outside of the circle, like [here]( https://eisman.github.io/neo4jd3/)
